dist: xenial

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip3 install -r test-requirements.txt
  - pip3 install -r requirements.txt
  - pip3 install tox-travis

script:
  - tox

after_success:
  - coveralls
